// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cateiru/cateir.com/ent/notice"
	"github.com/cateiru/cateir.com/ent/predicate"
)

// NoticeUpdate is the builder for updating Notice entities.
type NoticeUpdate struct {
	config
	hooks    []Hook
	mutation *NoticeMutation
}

// Where appends a list predicates to the NoticeUpdate builder.
func (nu *NoticeUpdate) Where(ps ...predicate.Notice) *NoticeUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetDiscordWebhook sets the "discord_webhook" field.
func (nu *NoticeUpdate) SetDiscordWebhook(s string) *NoticeUpdate {
	nu.mutation.SetDiscordWebhook(s)
	return nu
}

// SetNillableDiscordWebhook sets the "discord_webhook" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableDiscordWebhook(s *string) *NoticeUpdate {
	if s != nil {
		nu.SetDiscordWebhook(*s)
	}
	return nu
}

// ClearDiscordWebhook clears the value of the "discord_webhook" field.
func (nu *NoticeUpdate) ClearDiscordWebhook() *NoticeUpdate {
	nu.mutation.ClearDiscordWebhook()
	return nu
}

// SetSlackWebhook sets the "slack_webhook" field.
func (nu *NoticeUpdate) SetSlackWebhook(s string) *NoticeUpdate {
	nu.mutation.SetSlackWebhook(s)
	return nu
}

// SetNillableSlackWebhook sets the "slack_webhook" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableSlackWebhook(s *string) *NoticeUpdate {
	if s != nil {
		nu.SetSlackWebhook(*s)
	}
	return nu
}

// ClearSlackWebhook clears the value of the "slack_webhook" field.
func (nu *NoticeUpdate) ClearSlackWebhook() *NoticeUpdate {
	nu.mutation.ClearSlackWebhook()
	return nu
}

// SetMail sets the "mail" field.
func (nu *NoticeUpdate) SetMail(s string) *NoticeUpdate {
	nu.mutation.SetMail(s)
	return nu
}

// SetNillableMail sets the "mail" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableMail(s *string) *NoticeUpdate {
	if s != nil {
		nu.SetMail(*s)
	}
	return nu
}

// ClearMail clears the value of the "mail" field.
func (nu *NoticeUpdate) ClearMail() *NoticeUpdate {
	nu.mutation.ClearMail()
	return nu
}

// SetCreated sets the "created" field.
func (nu *NoticeUpdate) SetCreated(t time.Time) *NoticeUpdate {
	nu.mutation.SetCreated(t)
	return nu
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableCreated(t *time.Time) *NoticeUpdate {
	if t != nil {
		nu.SetCreated(*t)
	}
	return nu
}

// SetModified sets the "modified" field.
func (nu *NoticeUpdate) SetModified(t time.Time) *NoticeUpdate {
	nu.mutation.SetModified(t)
	return nu
}

// Mutation returns the NoticeMutation object of the builder.
func (nu *NoticeUpdate) Mutation() *NoticeMutation {
	return nu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NoticeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	nu.defaults()
	if len(nu.hooks) == 0 {
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NoticeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			if nu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NoticeUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NoticeUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NoticeUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NoticeUpdate) defaults() {
	if _, ok := nu.mutation.Modified(); !ok {
		v := notice.UpdateDefaultModified()
		nu.mutation.SetModified(v)
	}
}

func (nu *NoticeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notice.Table,
			Columns: notice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: notice.FieldID,
			},
		},
	}
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.DiscordWebhook(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldDiscordWebhook,
		})
	}
	if nu.mutation.DiscordWebhookCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldDiscordWebhook,
		})
	}
	if value, ok := nu.mutation.SlackWebhook(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldSlackWebhook,
		})
	}
	if nu.mutation.SlackWebhookCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldSlackWebhook,
		})
	}
	if value, ok := nu.mutation.Mail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldMail,
		})
	}
	if nu.mutation.MailCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldMail,
		})
	}
	if value, ok := nu.mutation.Created(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldCreated,
		})
	}
	if value, ok := nu.mutation.Modified(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldModified,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// NoticeUpdateOne is the builder for updating a single Notice entity.
type NoticeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoticeMutation
}

// SetDiscordWebhook sets the "discord_webhook" field.
func (nuo *NoticeUpdateOne) SetDiscordWebhook(s string) *NoticeUpdateOne {
	nuo.mutation.SetDiscordWebhook(s)
	return nuo
}

// SetNillableDiscordWebhook sets the "discord_webhook" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableDiscordWebhook(s *string) *NoticeUpdateOne {
	if s != nil {
		nuo.SetDiscordWebhook(*s)
	}
	return nuo
}

// ClearDiscordWebhook clears the value of the "discord_webhook" field.
func (nuo *NoticeUpdateOne) ClearDiscordWebhook() *NoticeUpdateOne {
	nuo.mutation.ClearDiscordWebhook()
	return nuo
}

// SetSlackWebhook sets the "slack_webhook" field.
func (nuo *NoticeUpdateOne) SetSlackWebhook(s string) *NoticeUpdateOne {
	nuo.mutation.SetSlackWebhook(s)
	return nuo
}

// SetNillableSlackWebhook sets the "slack_webhook" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableSlackWebhook(s *string) *NoticeUpdateOne {
	if s != nil {
		nuo.SetSlackWebhook(*s)
	}
	return nuo
}

// ClearSlackWebhook clears the value of the "slack_webhook" field.
func (nuo *NoticeUpdateOne) ClearSlackWebhook() *NoticeUpdateOne {
	nuo.mutation.ClearSlackWebhook()
	return nuo
}

// SetMail sets the "mail" field.
func (nuo *NoticeUpdateOne) SetMail(s string) *NoticeUpdateOne {
	nuo.mutation.SetMail(s)
	return nuo
}

// SetNillableMail sets the "mail" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableMail(s *string) *NoticeUpdateOne {
	if s != nil {
		nuo.SetMail(*s)
	}
	return nuo
}

// ClearMail clears the value of the "mail" field.
func (nuo *NoticeUpdateOne) ClearMail() *NoticeUpdateOne {
	nuo.mutation.ClearMail()
	return nuo
}

// SetCreated sets the "created" field.
func (nuo *NoticeUpdateOne) SetCreated(t time.Time) *NoticeUpdateOne {
	nuo.mutation.SetCreated(t)
	return nuo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableCreated(t *time.Time) *NoticeUpdateOne {
	if t != nil {
		nuo.SetCreated(*t)
	}
	return nuo
}

// SetModified sets the "modified" field.
func (nuo *NoticeUpdateOne) SetModified(t time.Time) *NoticeUpdateOne {
	nuo.mutation.SetModified(t)
	return nuo
}

// Mutation returns the NoticeMutation object of the builder.
func (nuo *NoticeUpdateOne) Mutation() *NoticeMutation {
	return nuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NoticeUpdateOne) Select(field string, fields ...string) *NoticeUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notice entity.
func (nuo *NoticeUpdateOne) Save(ctx context.Context) (*Notice, error) {
	var (
		err  error
		node *Notice
	)
	nuo.defaults()
	if len(nuo.hooks) == 0 {
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NoticeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			if nuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, nuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Notice)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from NoticeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NoticeUpdateOne) SaveX(ctx context.Context) *Notice {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NoticeUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NoticeUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NoticeUpdateOne) defaults() {
	if _, ok := nuo.mutation.Modified(); !ok {
		v := notice.UpdateDefaultModified()
		nuo.mutation.SetModified(v)
	}
}

func (nuo *NoticeUpdateOne) sqlSave(ctx context.Context) (_node *Notice, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notice.Table,
			Columns: notice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: notice.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notice.FieldID)
		for _, f := range fields {
			if !notice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.DiscordWebhook(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldDiscordWebhook,
		})
	}
	if nuo.mutation.DiscordWebhookCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldDiscordWebhook,
		})
	}
	if value, ok := nuo.mutation.SlackWebhook(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldSlackWebhook,
		})
	}
	if nuo.mutation.SlackWebhookCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldSlackWebhook,
		})
	}
	if value, ok := nuo.mutation.Mail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldMail,
		})
	}
	if nuo.mutation.MailCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldMail,
		})
	}
	if value, ok := nuo.mutation.Created(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldCreated,
		})
	}
	if value, ok := nuo.mutation.Modified(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldModified,
		})
	}
	_node = &Notice{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
