// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/cateiru/cateir.com/ent/notice"
)

// Notice is the model entity for the Notice schema.
type Notice struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notice) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case notice.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Notice", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notice fields.
func (n *Notice) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Notice.
// Note that you need to call Notice.Unwrap() before calling this method if this Notice
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Notice) Update() *NoticeUpdateOne {
	return (&NoticeClient{config: n.config}).UpdateOne(n)
}

// Unwrap unwraps the Notice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Notice) Unwrap() *Notice {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notice is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Notice) String() string {
	var builder strings.Builder
	builder.WriteString("Notice(")
	builder.WriteString(fmt.Sprintf("id=%v", n.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Notices is a parsable slice of Notice.
type Notices []*Notice

func (n Notices) config(cfg config) {
	for _i := range n {
		n[_i].config = cfg
	}
}
