// Code generated by ent, DO NOT EDIT.

package biography

const (
	// Label holds the string label denoting the biography type in the database.
	Label = "biography"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the biography in the database.
	Table = "biographies"
)

// Columns holds all SQL columns for biography fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
