# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  next:
    name: next build and lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env: 
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v1
      
      - name: Install packages
        run: yarn install
        
      - name: Lint
        run: yarn lint
        
      - name: Build
        run: yarn build
  go:
    name: go build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env: 
      TZ: "Asia/Tokyo"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build
      working-directory: ./api
      run: go build -v ./...

    - name: Test
      run: go test ./... -v -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
